/* =========================================================
   DATOS HIPOTÉTICOS DE LA TIENDA
   Cambia números de WhatsApp, precios, stock, imágenes, etc.
   ========================================================= */

// Número de WhatsApp de la tienda (formato internacional sin + ni espacios)
const WHATSAPP_NUMBER = "573000000000";

// Categorías con su ícono (emoji provisional mientras pones imágenes)
const CATEGORIES = [
  { name: "Protección", icon: "🧤" },
  { name: "Oxigenoterapia", icon: "💨" },
  { name: "Órtesis y Ortopedia", icon: "🦿" },
  { name: "Movilidad humana", icon: "🦯" },
  { name: "Medias", icon: "🧦" },
  { name: "Insumos médicos", icon: "🩺" },
  { name: "Fisioterapia y rehabilitación", icon: "💪" },
  { name: "Equipos médicos", icon: "🩻" },
  { name: "Cuidado personal y bienestar", icon: "🦶" },
];

// Slides del banner principal
const SLIDES = [
  {
    title: "Sillas de ruedas",
    text: "Diseñadas para maximizar la independencia. Con un diseño ergonómico que facilita la movilidad diaria con <strong>comodidad y resistencia</strong>.",
    emoji: "♿",
  },
  {
    title: "Órtesis y soportes",
    text: "Productos ortopédicos para <strong>recuperación y prevención</strong>. Encuentra el soporte ideal para tu tratamiento.",
    emoji: "🦿",
  },
  {
    title: "Oxigenoterapia en casa",
    text: "Equipos de oxígeno confiables para el <strong>cuidado respiratorio</strong> en la comodidad de tu hogar.",
    emoji: "💨",
  },
];

/* Cada producto:
   - id, name, category, brand
   - price (precio actual) y oldPrice (precio antes, para mostrar descuento)
   - stock (número). Si es 0 => "Agotado"
   - sizes: array de tallas (opcional)
   - colors: array {name, hex} (opcional)
   - rating y reviews[] (reseñas falsas)
   - desc: descripción
   - emoji: placeholder mientras se pone imagen real
   - img: ruta de imagen (déjalo "" para usar el recuadro con emoji)
*/
const PRODUCTS = [
  {
    id: 1,
    name: "Guante Nitrilo",
    category: "Protección",
    brand: "SafeCare",
    price: 30000,
    oldPrice: 38000,
    stock: 24,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Negro", hex: "#222" }, { name: "Azul", hex: "#2a5db0" }],
    rating: 4.8,
    desc: "Caja x100 unidades. Guantes de nitrilo sin polvo, alta resistencia y sensibilidad táctil. Ideal para uso médico y aseo.",
    emoji: "🧤",
    img: "",
    reviews: [
      { user: "María G.", stars: 5, text: "Excelente calidad, muy resistentes." },
      { user: "Carlos R.", stars: 4, text: "Buenos guantes, tallaje justo." },
    ],
  },
  {
    id: 2,
    name: "Polainas Antideslizantes",
    category: "Protección",
    brand: "MediStep",
    price: 12000,
    oldPrice: 0,
    stock: 0,
    sizes: ["Única"],
    colors: [{ name: "Azul", hex: "#2a5db0" }],
    rating: 4.2,
    desc: "Cubre calzado desechable con banda antideslizante. Paquete x50 unidades.",
    emoji: "🥾",
    img: "",
    reviews: [
      { user: "Ana P.", stars: 4, text: "Cumplen su función perfectamente." },
    ],
  },
  {
    id: 3,
    name: "Tapa Oídos Espuma",
    category: "Protección",
    brand: "SilentPro",
    price: 2000,
    oldPrice: 3000,
    stock: 120,
    sizes: [],
    colors: [{ name: "Naranja", hex: "#ff7a1a" }],
    rating: 4.6,
    desc: "Tapones auditivos de espuma de alta densidad. Reducción de ruido cómoda para dormir o trabajar.",
    emoji: "🔶",
    img: "",
    reviews: [
      { user: "Jorge M.", stars: 5, text: "Muy cómodos, bloquean bastante el ruido." },
      { user: "Laura V.", stars: 4, text: "Buenos por el precio." },
    ],
  },
  {
    id: 4,
    name: "Tapabocas Begut x50",
    category: "Protección",
    brand: "Begut",
    price: 18000,
    oldPrice: 20000,
    stock: 8,
    sizes: [],
    colors: [{ name: "Azul", hex: "#2a5db0" }, { name: "Blanco", hex: "#f2f2f2" }],
    rating: 4.7,
    desc: "Tapabocas de 3 capas con filtro. Caja x50 unidades, elástico suave y ajuste nasal.",
    emoji: "😷",
    img: "",
    reviews: [
      { user: "Diana S.", stars: 5, text: "Buena protección y no aprietan." },
    ],
  },
  {
    id: 5,
    name: "Concentrador de Oxígeno 5L",
    category: "Oxigenoterapia",
    brand: "OxyLife",
    price: 2500000,
    oldPrice: 2800000,
    stock: 3,
    sizes: [],
    colors: [{ name: "Blanco", hex: "#f2f2f2" }],
    rating: 4.9,
    desc: "Concentrador de oxígeno de 5 litros por minuto para uso domiciliario. Bajo consumo y funcionamiento silencioso.",
    emoji: "💨",
    img: "",
    reviews: [
      { user: "Pedro L.", stars: 5, text: "Funciona perfecto, muy silencioso." },
      { user: "Rosa T.", stars: 5, text: "Nos ha servido muchísimo en casa." },
    ],
  },
  {
    id: 6,
    name: "Cánula Nasal Adulto",
    category: "Oxigenoterapia",
    brand: "AirMed",
    price: 8000,
    oldPrice: 0,
    stock: 45,
    sizes: [],
    colors: [{ name: "Transparente", hex: "#dbe9f5" }],
    rating: 4.5,
    desc: "Cánula nasal de oxígeno para adulto, tubo de 2 metros. Material suave hipoalergénico.",
    emoji: "🫁",
    img: "",
    reviews: [{ user: "Luis F.", stars: 4, text: "Cómoda y buen material." }],
  },
  {
    id: 7,
    name: "Rodillera Ortopédica",
    category: "Órtesis y Ortopedia",
    brand: "OrthoFlex",
    price: 45000,
    oldPrice: 60000,
    stock: 15,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Negro", hex: "#222" }, { name: "Gris", hex: "#888" }],
    rating: 4.6,
    desc: "Rodillera con soporte lateral y banda rotuliana. Ideal para recuperación de lesiones y soporte deportivo.",
    emoji: "🦿",
    img: "",
    reviews: [
      { user: "Andrés C.", stars: 5, text: "Me ayudó mucho con el dolor de rodilla." },
      { user: "Sofía R.", stars: 4, text: "Buen soporte, tela cómoda." },
    ],
  },
  {
    id: 8,
    name: "Faja Lumbar",
    category: "Órtesis y Ortopedia",
    brand: "BackSupport",
    price: 55000,
    oldPrice: 70000,
    stock: 0,
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Negro", hex: "#222" }],
    rating: 4.4,
    desc: "Faja lumbar con varillas de soporte. Alivia dolor de espalda baja y mejora la postura.",
    emoji: "🩹",
    img: "",
    reviews: [{ user: "Marta D.", stars: 4, text: "Firme y cómoda para trabajar." }],
  },
  {
    id: 9,
    name: "Silla de Ruedas Estándar",
    category: "Movilidad humana",
    brand: "MoviCare",
    price: 480000,
    oldPrice: 550000,
    stock: 5,
    sizes: [],
    colors: [{ name: "Negro", hex: "#222" }, { name: "Azul", hex: "#2a5db0" }],
    rating: 4.7,
    desc: "Silla de ruedas plegable en acero, apoyabrazos fijos y frenos manuales. Capacidad hasta 100 kg.",
    emoji: "♿",
    img: "",
    reviews: [
      { user: "Gloria M.", stars: 5, text: "Resistente y fácil de plegar." },
      { user: "Hernán P.", stars: 4, text: "Buena relación calidad-precio." },
    ],
  },
  {
    id: 10,
    name: "Bastón Ajustable",
    category: "Movilidad humana",
    brand: "MoviCare",
    price: 35000,
    oldPrice: 42000,
    stock: 20,
    sizes: [],
    colors: [{ name: "Negro", hex: "#222" }, { name: "Plateado", hex: "#c0c0c0" }],
    rating: 4.5,
    desc: "Bastón de aluminio con altura ajustable y puño ergonómico antideslizante.",
    emoji: "🦯",
    img: "",
    reviews: [{ user: "Beatriz L.", stars: 5, text: "Ligero y muy estable." }],
  },
  {
    id: 11,
    name: "Medias de Compresión",
    category: "Medias",
    brand: "VenaFit",
    price: 40000,
    oldPrice: 50000,
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Negro", hex: "#222" }, { name: "Beige", hex: "#d8c3a5" }],
    rating: 4.8,
    desc: "Medias de compresión graduada 15-20 mmHg. Mejoran la circulación y reducen la fatiga en las piernas.",
    emoji: "🧦",
    img: "",
    reviews: [
      { user: "Camila R.", stars: 5, text: "Alivian mucho la pesadez de piernas." },
      { user: "Nubia G.", stars: 5, text: "Excelente compresión, buena tela." },
    ],
  },
  {
    id: 12,
    name: "Tensiómetro Digital",
    category: "Equipos médicos",
    brand: "HealthMeter",
    price: 95000,
    oldPrice: 120000,
    stock: 12,
    sizes: [],
    colors: [{ name: "Blanco", hex: "#f2f2f2" }],
    rating: 4.7,
    desc: "Tensiómetro digital de brazo automático con pantalla grande y memoria para 2 usuarios.",
    emoji: "🩺",
    img: "",
    reviews: [
      { user: "Óscar V.", stars: 5, text: "Preciso y fácil de usar." },
    ],
  },
  {
    id: 13,
    name: "Rodillo de Espuma",
    category: "Fisioterapia y rehabilitación",
    brand: "FisioPro",
    price: 38000,
    oldPrice: 0,
    stock: 18,
    sizes: [],
    colors: [{ name: "Azul", hex: "#2a5db0" }, { name: "Negro", hex: "#222" }],
    rating: 4.6,
    desc: "Rodillo de espuma de alta densidad para liberación miofascial y masaje muscular.",
    emoji: "🎯",
    img: "",
    reviews: [{ user: "Julián A.", stars: 5, text: "Ideal para estirar después de entrenar." }],
  },
  {
    id: 14,
    name: "Baja Lengua Madera x100",
    category: "Insumos médicos",
    brand: "MediWood",
    price: 9000,
    oldPrice: 11000,
    stock: 60,
    sizes: [],
    colors: [],
    rating: 4.3,
    desc: "Bajalenguas de madera estériles, paquete x100 unidades. Uso clínico y manualidades.",
    emoji: "🪵",
    img: "",
    reviews: [{ user: "Clínica Sur", stars: 4, text: "Buena calidad y precio." }],
  },
  {
    id: 15,
    name: "Separador de Dedos Gel",
    category: "Cuidado personal y bienestar",
    brand: "SoftFeet",
    price: 15000,
    oldPrice: 20000,
    stock: 25,
    sizes: [],
    colors: [{ name: "Transparente", hex: "#dbe9f5" }],
    rating: 4.5,
    desc: "Separador de dedos de gel para juanetes. Alivia la presión y corrige la alineación del dedo.",
    emoji: "🦶",
    img: "",
    reviews: [
      { user: "Patricia N.", stars: 5, text: "Muy cómodo, alivia el dolor del juanete." },
      { user: "Elena M.", stars: 4, text: "Suave, se ajusta bien." },
    ],
  },
];
